force-app/main/default/objects/Account_User_Login__c/Account_User_Login__c.object-meta.xml
<CustomObject>
    <description
  >Junction Object to connect Account and User Login.</description>
    <label>Account User Login</label>
    <nameField>
        <label>Account User Login Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account User Logins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_User_Login__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account for User Login.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account User Logins</relationshipLabel>
    <relationshipName>Account_User_Logins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_User_Login__c/fields/User_Login__c.field-meta.xml
<CustomField>
    <fullName>User_Login__c</fullName>
    <description>User login for an Account.</description>
    <label>User Login</label>
    <referenceTo>User_Login__c</referenceTo>
    <relationshipLabel>Account User Logins</relationshipLabel>
    <relationshipName>Account_User_Logins</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Login__c/User_Login__c.object-meta.xml
<CustomObject>
    <description
  >An object for storing passwords and login for Account Users.</description>
    <label>User Login</label>
    <nameField>
        <label>User Login Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Login__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email for a User.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Login__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <description>Login for a User.</description>
    <label>Login</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Login__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for a User.</description>
    <label>Password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/SiteAuthController/SiteAuthController.cls
public without sharing class SiteAuthController {
  private class UserNotFoundException extends Exception {
  }

  private class TokenHasExpiredException extends Exception {
  }

  private final String defaultToken = 'hello world';

  @AuraEnabled
  public static List<String> login(String loginOrEmail, String password) {
    try {
      List<Account_User_Login__c> lstAccountUserLogin = [
        SELECT Account__c, User_Login__r.Password__c, User_Login__r.Login__c
        FROM Account_User_Login__c
        WHERE
          User_Login__r.Login__c = :loginOrEmail
          OR User_Login__r.Email__c = :loginOrEmail
        WITH SECURITY_ENFORCED
      ];

      if (
        lstAccountUserLogin.size() == 0 ||
        lstAccountUserLogin[0].User_Login__r.Password__c != password
      ) {
        throw new UserNotFoundException('Invalid credentials!');
      }

      Account_User_Login__c acctUserLogin = lstAccountUserLogin[0];

      String token = generateSessionToken();
      String expirationDate = generateExpirationDate();

      // SET TOKEN AND EXPIRATION DATE
      // TO THE ACCOUNT LOGIN CUSTOM AUTH TO LATER AUTH BY IT

      List<String> accountAndToken = new List<String>{
        acctUserLogin.Account__c,
        token
      };

      return accountAndToken;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static string authenticate(String token) {
    try {
      List<Account_User_Login__c> lstAccountUserLogin = [
        // SELECT Custom Auth Token
        SELECT Account__c, User_Login__r.Password__c, User_Login__r.Login__c
        FROM Account_User_Login__c
        WHERE Token__c = :token
        WITH SECURITY_ENFORCED
      ];

      // IF TOKEN FOUND AND IT ISN'T EXPIRED
      // RETURN AccountId
      // OTHERWISE call throw exception

      throw new TokenHasExpiredException('Token has expired!');

      return '';
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  private string generateSessionToken() {
    // TODO: IMPROVE LOGIC FOR TOKEN GENERATION
    return defaultToken;
  }

  private Datetime generateExpirationDate() {
    // TODO: IMPROVE LOGIC FOR TOKEN GENERATION
    return new Datetime() + 1;
  }
}