force-app/main/default/objects/Account_User_Login__c/Account_User_Login__c.object-meta.xml
<CustomObject>
    <description
  >Junction Object to connect Account and User Login.</description>
    <label>Account User Login</label>
    <nameField>
        <label>Account User Login Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account User Logins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_User_Login__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account for User Login.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account User Logins</relationshipLabel>
    <relationshipName>Account_User_Logins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_User_Login__c/fields/User_Login__c.field-meta.xml
<CustomField>
    <fullName>User_Login__c</fullName>
    <description>User login for an Account.</description>
    <label>User Login</label>
    <referenceTo>User_Login__c</referenceTo>
    <relationshipLabel>Account User Logins</relationshipLabel>
    <relationshipName>Account_User_Logins</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Auth__c/Custom_Auth__c.object-meta.xml
<CustomObject>
    <label>Custom Auth</label>
    <nameField>
        <label>Custom Auth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Auths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Auth__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <description>Expiration Date for the Token</description>
    <label>Expires At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Custom_Auth__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Token for Custom Auth</description>
    <label>Token</label>
    <length>48</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Login__c/User_Login__c.object-meta.xml
<CustomObject>
    <description
  >An object for storing passwords and login for Account Users.</description>
    <label>User Login</label>
    <nameField>
        <label>User Login Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Login__c/fields/Custom_Auth__c.field-meta.xml
<CustomField>
    <fullName>Custom_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Custom Auth object containing token and expiration date.</description>
    <label>Custom Auth</label>
    <referenceTo>Custom_Auth__c</referenceTo>
    <relationshipLabel>User Logins</relationshipLabel>
    <relationshipName>User_Logins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Login__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email for a User.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Login__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <description>Login for a User.</description>
    <label>Login</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Login__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for a User.</description>
    <label>Password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/controllers/SiteAuthController/SiteAuthController.cls
public without sharing class SiteAuthController {
  private class UserNotFoundException extends Exception {
  }

  private class TokenHasExpiredException extends Exception {
  }

  private class InvalidTokenException extends Exception {
  }

  private static final String DEFAULT_TOKEN = 'hello world';

  @AuraEnabled
  public static List<String> login(String loginOrEmail, String password) {
    try {
      List<User_Login__c> lstUserLogin = [
        SELECT
          Id,
          Custom_Auth__c,
          Custom_Auth__r.Token__c,
          Custom_Auth__r.Expires_At__c,
          Login__c,
          Password__c,
          (SELECT Account__c FROM Account_User_Logins__r)
        FROM User_Login__c
        WHERE
          User_Login__c.Login__c = :loginOrEmail
          OR User_Login__c.Email__c = :loginOrEmail
      ];

      if (lstUserLogin.size() == 0 || lstUserLogin[0].Password__c != password) {
        throw new UserNotFoundException('Invalid credentials!');
      }

      User_Login__c userLogin = lstUserLogin[0];

      String token = generateSessionToken();
      Datetime expirationDate = generateExpirationDate();

      if (userLogin.Custom_Auth__c == null) {
        Custom_Auth__c customAuth = new Custom_Auth__c();
        customAuth.Token__c = token;
        customAuth.Expires_At__c = expirationDate;
        insert customAuth;
        userLogin.Custom_Auth__c = customAuth.Id;
        update userLogin;
      } else {
        List<Custom_Auth__c> lstCustomAuth = [
          SELECT Id, Token__c, Expires_At__c
          FROM Custom_Auth__c
          WHERE Id = :userLogin.Custom_Auth__c
        ];

        Custom_Auth__c customAuth = lstCustomAuth[0];
        customAuth.Token__c = token;
        customAuth.Expires_At__c = expirationDate;

        update customAuth;
      }

      List<String> accountAndToken = new List<String>{
        userLogin.Account_User_Logins__r[0].Account__c,
        token
      };

      return accountAndToken;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static String authenticate(String token) {
    try {
      List<User_Login__c> lstUserLogin = [
        SELECT
          Id,
          Custom_Auth__c,
          Custom_Auth__r.Token__c,
          Custom_Auth__r.Expires_At__c,
          Login__c,
          Password__c,
          (SELECT Account__c FROM Account_User_Logins__r)
        FROM User_Login__c
        WHERE Custom_Auth__r.Token__c = :token
      ];

      if (lstUserLogin.size() == 0) {
        throw new InvalidTokenException('Token is invalid');
      }

      User_Login__c userLogin = lstUserLogin[0];

      if (userLogin.Custom_Auth__r.Expires_At__c <= Datetime.now()) {
        throw new TokenHasExpiredException('Token has expired!');
      }

      return userLogin.Account_User_Logins__r[0].Account__c;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  private static String generateSessionToken() {
    return DEFAULT_TOKEN +
      String.valueOf(Integer.valueof((Math.random() * 1000)));
  }

  private static Datetime generateExpirationDate() {
    return Datetime.now().addDays(1);
  }
}