force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Custom Wrapper Object for Territory2.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory2Id__c.field-meta.xml
<CustomField>
    <fullName>Territory2Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Territory2Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WarehouseTerritory2Association__c/WarehouseTerritory2Association__c.object-meta.xml
<CustomObject>
    <label>WarehouseTerritory2Association</label>
    <nameField>
        <label>WarehouseTerritory2Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WarehouseTerritory2Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarehouseTerritory2Association__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>WarehouseTerritory2Associations</relationshipLabel>
    <relationshipName>WarehouseTerritory2Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WarehouseTerritory2Association__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>WarehouseTerritory2Associations</relationshipLabel>
    <relationshipName>WarehouseTerritory2Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controllers/UserController/UserController.cls
public without sharing class UserController {
  public static final String REGIONAL_MANAGER_ROLE = 'Regional Manager';
  public static final String SALES_MANAGER_ROLE = 'Sales Manager';

  @AuraEnabled(cacheable=true)
  public static Id getUserAssociatedWarehouse(String userId) {
    Id territory2Id = UserController.getUserAssociatedTerritory(userId);

    List<WarehouseTerritory2Association__c> lstWarehouseTerritory2Association = [
      SELECT Warehouse__c
      FROM WarehouseTerritory2Association__c
      WHERE Territory__r.Territory2Id__c = :territory2Id
    ];

    if (lstWarehouseTerritory2Association.size() > 0) {
      Id warehouseId = lstWarehouseTerritory2Association[0].Warehouse__c;
      return warehouseId;
    }

    return null;
  }

  @AuraEnabled(cacheable=true)
  public static Id getUserAssociatedTerritoryRegionalManager(String userId) {
    Id territory2Id = UserController.getUserAssociatedTerritory(userId);

    List<UserTerritory2Association> lstUserTerritory2Association = [
      SELECT UserId
      FROM UserTerritory2Association
      WHERE
        RoleInTerritory2 = :UserController.REGIONAL_MANAGER_ROLE
        AND Territory2Id = :territory2Id
    ];

    if (lstUserTerritory2Association.size() > 0) {
      return lstUserTerritory2Association[0].UserId;
    }

    return null;
  }

  public static Id getUserAssociatedTerritory(String userId) {
    List<UserTerritory2Association> lstUserTerritory2Association = [
      SELECT Territory2Id
      FROM UserTerritory2Association
      WHERE UserId = :userId
    ];

    if (lstUserTerritory2Association.size() > 0) {
      return lstUserTerritory2Association[0].Territory2Id;
    }

    return null;
  }

  @AuraEnabled(cacheable=true)
  public static List<UserDTO> getSalesManagersInUsersTerritory(String userId) {
    Id territory2Id = UserController.getUserAssociatedTerritory(userId);

    List<UserDTO> salesManagersInTerritory = Territory2Controller.getUsersInTerritoryByRole(
      territory2Id,
      UserController.SALES_MANAGER_ROLE
    );

    return salesManagersInTerritory;
  }
}