force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Custom Wrapper Object for Territory2.</description>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Territory2Id__c.field-meta.xml
<CustomField>
    <fullName>Territory2Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Territory2Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Territory2Handler/Territory2Handler.cls
public with sharing class Territory2Handler {
  public static void createTerritoryCustomObjects(
    List<Territory2> lstTriggerTerritory2
  ) {
    List<Territory__c> lstCustomTerritoryObjToInsert = new List<Territory__c>();

    List<Territory2> lstTerritory2 = [
      SELECT
        Id,
        Name,
        Territory2Type.MasterLabel,
        (SELECT Id FROM UserTerritory2Associations)
      FROM Territory2
      WHERE Id IN :lstTriggerTerritory2
      WITH SECURITY_ENFORCED
      LIMIT 5000
    ];

    for (Territory2 t : lstTerritory2) {
      Territory__c territory = new Territory__c();
      territory.Name = t.Name;
      territory.Label__c = t.Territory2Type.MasterLabel;
      territory.Territory2Id__c = t.Id;
      lstCustomTerritoryObjToInsert.add(territory);
    }

    insert lstCustomTerritoryObjToInsert;
  }
}