force-app/main/default/objects/Fulfillment_Request__c/Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <label>Fulfillment Request</label>
    <nameField>
        <label>Fulfillment Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment_Request__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipName>Fulfilment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FulfillmentRequestController/FulfillmentRequestController.cls
public with sharing class FulfillmentRequestController {
  @AuraEnabled(cacheable=true)
  public static List<FulfillmentRequestDTO> getFulfillmentRequestsForUserAssociatedWarehouse(
    String userId
  ) {
    Id warehouseId = UserController.getUserAssociatedWarehouse(userId);

    if (warehouseId == null) {
      return null;
    }

    Id locationId = WarehouseController.getWarehouseLocationId(warehouseId);

    if (locationId == null) {
      return null;
    }

    List<FulfillmentRequestDTO> lstFulfillmentRequestDTO = new List<FulfillmentRequestDTO>();

    for (Fulfillment_Request__c f : [
      SELECT Id
      FROM Fulfillment_Request__c
      WHERE LocationId__c = :locationId
      WITH SECURITY_ENFORCED
      ORDER BY CreatedDate DESC
    ]) {
      FulfillmentRequestDTO request = new FulfillmentRequestDTO();
      request.id = f.Id;
      lstFulfillmentRequestDTO.add(request);
    }

    return lstFulfillmentRequestDTO;
  }
}