force-app/main/default/objects/Fulfillment_Request__c/Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <label>Fulfillment Request</label>
    <nameField>
        <label>Fulfillment Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fulfilment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Request__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipName>Fulfilment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/handlers/FulfillmentRequestHandler/FulfillmentRequestHandler.cls
public with sharing class FulfillmentRequestHandler {
  private static final String FULFILLMENT_REQUESTED_DEVELOPER_NAME = 'Fulfillment_Requested';

  public static void sendFulfillmentRequestedNotificationToRegionalManagers(
    List<Fulfillment_Request__c> lstTriggerFulfillmentRequest
  ) {
    Id customNotificationId = Utils.getCustomNotificationByDeveloperName(
      FulfillmentRequestHandler.FULFILLMENT_REQUESTED_DEVELOPER_NAME
    );

    if (customNotificationId == null) {
      return;
    }

    List<Fulfillment_Request__c> lstFulfillmentRequest = [
      SELECT Id, OwnerId, LocationId__r.Name, Assigned_To__c
      FROM Fulfillment_Request__c
      WHERE Id IN :lstTriggerFulfillmentRequest
      WITH SECURITY_ENFORCED
      LIMIT 5000
    ];

    for (Fulfillment_Request__c f : lstFulfillmentRequest) {
      Messaging.CustomNotification notification = new Messaging.CustomNotification();
      notification.setTitle('New Fulfillment Request');
      notification.setBody('New Fulfilment Request on ' + f.LocationId__r.Name);
      notification.setNotificationTypeId(customNotificationId);
      notification.setTargetId(f.Id);
      notification.setSenderId(f.OwnerId);

      Set<String> recipientIds = new Set<String>();
      recipientIds.add(f.Assigned_To__c);

      notification.send(recipientIds);
    }
  }
}