force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WarehouseTerritory2Association__c/WarehouseTerritory2Association__c.object-meta.xml
<CustomObject>
    <label>WarehouseTerritory2Association</label>
    <nameField>
        <label>WarehouseTerritory2Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WarehouseTerritory2Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarehouseTerritory2Association__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>WarehouseTerritory2Associations</relationshipLabel>
    <relationshipName>WarehouseTerritory2Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controllers/LocationController/LocationController.cls
public with sharing class LocationController {
  @AuraEnabled(cacheable=true)
  public static List<ProductItemDTO> getLocationProductItmes(
    String locationId
  ) {
    Schema.Location location = [
      SELECT
        (
          SELECT
            Id,
            Product2.Id,
            Product2.Name,
            ProductItemNumber,
            QuantityOnHand,
            SerialNumber
          FROM ProductItems
        )
      FROM Location
      WHERE Id = :locationId
      WITH SECURITY_ENFORCED
      LIMIT 5000
    ];

    if (location.ProductItems.isEmpty()) {
      return null;
    }

    List<ProductItemDTO> lstProductItemDTO = new List<ProductItemDTO>();

    for (ProductItem p : location.ProductItems) {
      ProductItemDTO productItem = new ProductItemDTO();

      productItem.productId = p.Product2.Id;
      productItem.productItemId = p.Id;
      productItem.productItemNumber = p.ProductItemNumber;
      productItem.productItemQuantity = p.QuantityOnHand;
      productItem.productItemSerialNumber = p.SerialNumber;
      productItem.productName = p.Product2.Name;
      productItem.productUrl = Utils.getObjectURL(p.Product2.Id);
      productItem.productItemUrl = Utils.getObjectURL(p.Id);

      lstProductItemDTO.add(productItem);
    }

    return lstProductItemDTO;
  }

  public static Map<Id, Set<String>> getLocationRegionalManagers() {
    Map<Id, Id> territory2LocationMap = new Map<Id, Id>();

    for (WarehouseTerritory2Association__c wta : [
      SELECT Warehouse__c.LocationId__c, Territory_r.Territory2Id__c
      FROM WarehouseTerritory2Association__c
      WITH SECURITY_ENFORCED
      LIMIT 5000
    ]) {
      territory2LocationMap.put(
        wta.Territory_r.Territory2Id__c,
        wta.Warehouse__c.LocationId__c
      );
    }

    Map<Id, Set<Id>> territory2RegionalManagerMap = new Map<Id, Set<Id>>();

    for (UserTerritory2Association uta : [
      SELECT UserId, Territory2Id
      FROM UserTerritory2Association
      WHERE roleInTerritory2 = :UserController.REGIONAL_MANAGER_ROLE
      WITH SECURITY_ENFORCED
      LIMIT 5000
    ]) {
      Set<Id> regionalManagers = territory2RegionalManagerMap.get(
        uta.Territory2Id
      );
      if (regionalManagers == null) {
        Set<Id> regionalManagers = new Set<Id>{ uta.UserId };
        territory2RegionalManagerMap.put(uta.Territory2Id, regionalManagers);
      } else {
        regionalManagers.add(uta.UserId);
      }
    }

    Map<Id, Set<String>> locationRegionalManagerMap = new Map<Id, Set<String>>();

    for (Id key : territory2LocationMap.keySet()) {
      Id locationId = territory2LocationMap.get(Id);
      Set<Id> userIds = territory2RegionalManagerMap.get(Id);
      locationRegionalManagerMap.put(locationId, userIds);
    }

    return locationRegionManagerMap;
  }
}